server:
  port: 10101
  compression:
    enabled: true
    mime-types: application/x-protobuf

spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: org.sqlite.JDBC

async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 15
      # 配置队列大小
      queue_capacity: 999
      # 配置线程最大空闲时间
      keep_alive_seconds: 30
      # 配置线程池中的线程的名称前缀
      name:
        prefix: qmjy-async-

logging:
  level:
    #    org.springframework.web: trace
    org.springframework.web: info

# 数据存放目录
data-path: