server:
  port: 10101

spring:
  mvc:
    static-path-pattern: /**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:mapbox/tilesets/default.mbtiles

logging:
  level:
    #    org.springframework.web: trace
    org.springframework.web: info

# 数据存放目录
data-path: