server:
  port: 10101
  compression:
    enabled: true
    mime-types: application/x-protobuf

spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 5GB

async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 2
      # 配置最大线程数
      max_pool_size: 5
      # 配置队列大小
      queue_capacity: 50
      # 配置线程最大空闲时间
      keep_alive_seconds: 30
      # 配置线程池中的线程的名称前缀
      name:
        prefix: qmjy-async-

logging:
  level:
    #    org.springframework.web: trace
    org.springframework.web: info

osmwrangle:
  #Possible input formats: OSM_XML, OSM_PBF
  inputFormat: OSM_PBF
  #Default conversion mode: (in-memory) STREAM
  mode: STREAM
  mapping_file: /wrangle/Attribute_mapping.conf
  tmpDir: /tmp
  outputDir: /output

# 数据存放目录
data-path:
# 开启默认图片
enable-default-tile: false
# 从mvt的pbf提取poi数据
enable-poi-extract-mvt: false
enable-poi-extract-osm-pbf: false
# 启用路径规划
enable-planning: false