server:
  port: 10101

spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:default.db

logging:
  level:
    org.springframework.web: trace

mapbox:
  styles:
  tilesets:
  sprites:
  fonts:
  assets: