spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:default.db

server:
  port: 6666

mapbox:
  styles:
  tilesets:
  sprites:
  fonts:
  assets: