server:
  port: 10101

spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:tilesets/default.mbtiles

logging:
  level:
    #    org.springframework.web: trace
    org.springframework.web: info

# 数据存放目录
config: /test